"""Docker Compose file generator."""

import dataclasses
import re
from collections.abc import KeysView
from pathlib import Path
from typing import Any

import yaml
from loguru import logger
from rich.console import Console

from localbox.config import Solution
from localbox.models.base_env import BaseEnv, EnvField, EnvRef
from localbox.models.builder import BindVolume, CacheVolume, NamedVolume, Volume
from localbox.models.service import Service

_ENV_REF_RE = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}")

console = Console()


class _QuotedStr(str):
    """str subclass that serializes as a double-quoted YAML scalar."""


class _NoAliasDumper(yaml.SafeDumper):
    """YAML dumper with no anchors/aliases and consistent sequence indentation."""

    def ignore_aliases(self, data: Any) -> bool:
        return True

    def increase_indent(self, flow: bool = False, indentless: bool = False) -> None:
        # Force indented sequences so list items always indent under their key
        return super().increase_indent(flow=flow, indentless=False)


_NoAliasDumper.add_representer(
    _QuotedStr,
    lambda dumper, data: dumper.represent_scalar("tag:yaml.org,2002:str", data, style='"'),
)

# EnvRef is a str subclass carrying side-channel raw-value data, but PyYAML
# looks up representers by exact type (not inheritance), so without this line
# any EnvRef that reaches yaml.dump (ports, hostname, extras, bare values
# passed directly rather than via f-string) raises RepresenterError. Serialize
# it as a plain YAML string — its textual value is already "${NAME}".
_NoAliasDumper.add_representer(
    EnvRef,
    lambda dumper, data: dumper.represent_scalar("tag:yaml.org,2002:str", str(data)),
)


def _quote_env_value(value: str) -> str:
    """Quote a value for .env file using double quotes with all special chars escaped.

    Escapes characters that would cause shell substitution or command execution:
      \\  ->  \\\\   (must be first to avoid double-escaping)
      "   ->  \\"
      $   ->  \\$   (prevents ${var} and $(...) substitution)
      `   ->  \\`   (prevents backtick command substitution)
    """
    escaped = (
        value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("`", "\\`")
    )
    return f'"{escaped}"'


def _write_env_file(path: Path, env_vars: dict[str, str]) -> None:
    """Write KEY='value' pairs to .env file. No-ops if env_vars is empty."""
    if not env_vars:
        return
    lines = [
        "# Generated by localbox compose generate",
        "# Source of truth: solution.py / solution-override.py",
        "# Do not edit — regenerated on each run",
        "",
    ]
    for k in sorted(env_vars):
        lines.append(f"{k}={_quote_env_value(env_vars[k])}")
    path.write_text("\n".join(lines) + "\n")


def _ensure_gitignored(solution_root: Path, entries: list[str]) -> None:
    """Ensure entries are present in solution_root/.gitignore."""
    gitignore = solution_root / ".gitignore"
    if gitignore.exists():
        content = gitignore.read_text()
        existing = set(content.splitlines())
    else:
        content = ""
        existing = set()

    to_add = [e for e in entries if e not in existing]
    if not to_add:
        return

    if content and not content.endswith("\n"):
        content += "\n"
    content += "\n".join(to_add) + "\n"
    gitignore.write_text(content)


def _collect_all_solution_env_vars(solution: Solution) -> dict[str, str]:
    """Collect all env vars defined in SolutionConfig.env.

    For BaseEnv instances, all fields that were set are collected via
    ``raw_values()``. Fields still holding the ``EnvField`` sentinel are
    silently skipped here — the walker raises when such a field is actually
    referenced in a compose value.
    For plain dicts, all non-None values are collected.
    """
    env = solution.config.env if solution.config else None
    if not env:
        return {}

    result: dict[str, str] = {}

    if isinstance(env, BaseEnv):
        # raw_values() only contains fields that were actually set. Unset
        # required fields are caught by the reference walker when/if they
        # are referenced in a compose field.
        result.update(env.raw_values())
    elif isinstance(env, dict):
        for k, v in env.items():
            if v is not None:
                result[k] = v

    return result


def _baseenv_field_names(env_instance: Any) -> set[str]:
    """Return the set of field names declared on a BaseEnv instance."""
    if not isinstance(env_instance, BaseEnv):
        return set()
    return {f.name for f in dataclasses.fields(env_instance)}


def _walk_env_refs(
    value: Any,
    env_instance: Any,
    collector: dict[str, str],
) -> None:
    """Walk a compose structure and collect BaseEnv references found in strings.

    For every string value that contains one or more ``${NAME}`` tokens, each
    captured ``NAME`` that is a declared field of ``env_instance`` is looked
    up via ``env_instance.raw_value(NAME)`` and added to ``collector``.

    Raises ``ValueError`` if a referenced field exists on the BaseEnv subclass
    but was never set (i.e. still holds the ``EnvField`` sentinel).

    References whose name does not match any field on ``env_instance`` are
    left untouched — they are treated as Docker Compose's own variable
    expansion and flow through verbatim.
    """
    if isinstance(value, dict):
        for v in value.values():
            _walk_env_refs(v, env_instance, collector)
        return
    if isinstance(value, (list, tuple)):
        for v in value:
            _walk_env_refs(v, env_instance, collector)
        return
    if not isinstance(value, str):
        return

    field_names = _baseenv_field_names(env_instance)
    if not field_names:
        return

    for match in _ENV_REF_RE.finditer(value):
        name = match.group(1)
        if name not in field_names:
            continue
        try:
            collector[name] = env_instance.raw_value(name)
        except KeyError as exc:
            raise ValueError(
                f"Env.{name} is required but not set. "
                f"Set it in solution.py or solution-override.py."
            ) from exc


def generate_compose_file(solution: Solution) -> Path:
    """
    Generate docker-compose.yml in solution root.

    Returns path to generated compose file.
    """
    # Generate docker-compose.yml
    solution.directories.compose.mkdir(parents=True, exist_ok=True)
    # TRD says generate in solution root.

    compose: dict[str, Any] = {
        "name": solution.docker.compose_project,
        "services": {},
        "networks": {
            solution.docker.network: {
                "driver": "bridge",
            }
        },
        "volumes": {},
    }

    logger.info("generating compose file for {} services", len(solution.services))
    # Sort services by order
    services = sorted(solution.services.values(), key=lambda s: s.compose.order)

    env_vars: dict[str, str] = {}

    for service in services:
        service_name = service.compose_name
        service_def = generate_service_definition(solution, service, env_collector=env_vars)
        compose["services"][service_name] = service_def

        # Collect named volumes for top-level declaration
        for volume in service.compose.volumes:
            if isinstance(volume, NamedVolume):
                compose["volumes"][volume.name] = {}

    # Write compose file
    compose_file = solution.root / "docker-compose.yml"

    raw = yaml.dump(compose, Dumper=_NoAliasDumper, default_flow_style=False, sort_keys=False)

    with open(compose_file, "w") as f:
        f.write(_format_compose_yaml(raw, compose["services"].keys()))

    logger.info("compose file written to {}", compose_file)
    console.print(f"[green]Generated[/green] {compose_file}")

    # Merge solution-level env vars with service-collected env vars
    solution_env_vars = _collect_all_solution_env_vars(solution)
    all_env_vars = {**solution_env_vars, **env_vars}

    if all_env_vars:
        env_file = solution.root / ".env"
        _write_env_file(env_file, all_env_vars)
        console.print(f"[green]Generated[/green] {env_file}")

    # Ensure both files are gitignored
    _ensure_gitignored(solution.root, ["docker-compose.yml", ".env"])

    return compose_file


def _format_compose_yaml(yaml_text: str, service_names: KeysView[str]) -> str:
    """Format the raw yaml.dump output for docker-compose readability.

    - Inserts blank lines before each service entry (only within the services block)
    - Inserts blank lines before top-level section headers (networks:, volumes:)
    - Fixes empty-dict representation from '{ }' to '{}'
    """
    lines = yaml_text.splitlines(keepends=True)
    result: list[str] = []
    service_keys = {f"  {name}:" for name in service_names}
    section_headers = {"networks:", "volumes:"}

    in_services_block = False

    for line in lines:
        stripped = line.rstrip()

        # Detect top-level block transitions (no leading whitespace, ends with ':')
        if not line[0:1].isspace() and stripped.endswith(":"):
            key = stripped.split(":")[0]
            in_services_block = key == "services"

            if stripped in section_headers and result:
                result.append("\n")

        # Blank line before each service — only inside the services: block
        elif in_services_block and stripped in service_keys:
            result.append("\n")

        result.append(line)

    text = "".join(result)
    # Normalize empty-dict representation that PyYAML emits as '{ }'
    text = text.replace("{ }", "{}")
    return text


def _relative_if_inside(path: Path, root: Path) -> str:
    """Return a ./-prefixed relative path if path is inside root, else absolute string."""
    try:
        return "./" + str(path.relative_to(root))
    except ValueError:
        return str(path)


def _render_volume(vol: Volume, solution: Solution) -> str:
    """Render a Volume as a docker-compose volume string."""
    if isinstance(vol, NamedVolume):
        mount = f"{vol.name}:{vol.container}"
    elif isinstance(vol, CacheVolume):
        host = solution.directories.build / vol.name
        host.mkdir(parents=True, exist_ok=True)
        mount = f"{_relative_if_inside(host, solution.root)}:{vol.container}"
    elif isinstance(vol, BindVolume):
        host = Path(vol.host)
        if not host.is_absolute():
            host = solution.root / host
        mount = f"{_relative_if_inside(host, solution.root)}:{vol.container}"
    else:
        raise ValueError(f"Unknown volume type: {type(vol)}")
    if vol.readonly:
        mount += ":ro"
    return mount


def generate_service_definition(
    solution: Solution,
    service: Service,
    env_collector: dict[str, str] | None = None,
) -> dict:
    """Generate docker-compose service definition."""
    # Base definition (no container_name to allow scaling)
    service_def: dict = {
        "networks": [solution.docker.network],
    }

    # Passthrough extra fields (named fields below will override conflicts)
    service_def.update(service.compose.extra)

    # Hostname
    if service.compose.hostname:
        service_def["hostname"] = service.compose.hostname

    # Profiles — auto-derived from service group, colons replaced with dashes
    # e.g. group "db" -> profile "db", group "be:payments" -> profile "be-payments"
    # Services without a group have no profile and always start.
    # TODO: profiles temporarily disabled
    # if service.group:
    #     service_def["profiles"] = [service.group.replace(":", "-")]

    # Image: use explicit image name if set, otherwise auto-generate tag
    # Use image.name (logical name) to derive tag if dockerfile logic was used
    # If image.image is present but no dockerfile, we pull & tag.
    # The tag used is <solution>/service/<name>:latest

    # We should use the tag generated/expected by prepare_docker_image
    # Tag logic: f"{solution.name}/service/{service.image.name}:latest"

    if service.image.name:
        service_def["image"] = solution.service_image_tag(service.image.name)
    elif service.image.image:
        # Fallback if name not set (shouldn't happen with new validation)
        service_def["image"] = service.image.image
    else:
        # Fallback: derive tag the same way _finalize_image_name would
        image_name = (service.name or "").replace(":", "/")
        service_def["image"] = solution.service_image_tag(image_name)

    # Ports
    if service.compose.ports:
        service_def["ports"] = service.compose.ports

    # Environment — values flow through the generic reference walker at the
    # end of this function. We reject class-level EnvField sentinels here
    # because users must reference env fields via instance access.
    if service.compose.environment:
        resolved: dict[str, Any] = {}
        for k, v in service.compose.environment.items():
            if isinstance(v, EnvField):
                raise TypeError(
                    f"Service environment '{k}' received a class-level EnvField "
                    f"sentinel. Use instance access on the solution's env "
                    f"(e.g. config.env.{k}) instead of Env.{k}."
                )
            resolved[k] = _QuotedStr(v)
        service_def["environment"] = resolved

    # Volumes
    if service.compose.volumes:
        service_def["volumes"] = [_render_volume(v, solution) for v in service.compose.volumes]

    # Dependencies
    if service.compose.depends_on:
        depends = [dep.compose_name for dep in service.compose.depends_on]
        service_def["depends_on"] = depends

    # Links
    if service.compose.links:
        links = [
            link.replace(":", "-", 1) if ":" in link.split(":")[0] else link
            for link in service.compose.links
        ]
        service_def["links"] = links

    # Healthcheck
    if service.compose.healthcheck:
        service_def["healthcheck"] = service.compose.healthcheck.to_compose_dict()

    # Restart policy
    service_def["restart"] = "unless-stopped"

    # Walk the finished service definition for BaseEnv references so that the
    # .env file is populated for every field referenced in any compose value
    # (ports, environment, volumes, extras, healthcheck, links, ...). This
    # also raises ValueError when a referenced field is declared on the
    # BaseEnv subclass but was never set.
    env_instance = solution.config.env if solution.config else None
    if isinstance(env_instance, BaseEnv):
        sink = env_collector if env_collector is not None else {}
        _walk_env_refs(service_def, env_instance, sink)

    return service_def
